### ISSUE TITLE
Cinematic Studio StackOverflowError on Mohistmc

### ISSUE THREAD

**Issue by PeterMa1996** [PluginBugs/Issues-CinematicsStudio#1]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

1. When I play a scene, it can be finished, but I got the error below and after playing the scene, I can't move my mouse since it will be reset all the time.
```
[22:28:19 WARN]: [CinematicStudio] Task #3491 for CinematicStudio v1.4.3-r4 generated an exception
java.lang.StackOverflowError: null
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:556) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:556) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:556) ~[forge:?]
```

2. The config.yml file didn't get generated correctly, the content of the file only has 4 `NUL`s (null character)

### Steps to reproduce the issue

1. Install this plugin on Mohistmc
2. Create a scene
3. Play the scene

### CinematicsStudio Version

CinematicStudio version 1.4.3-r4

### ProtocolLib Version

ProtocoLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.21

### Error (optional)

```shell
[22:28:19 WARN]: [CinematicStudio] Task #3491 for CinematicStudio v1.4.3-r4 generated an exception
java.lang.StackOverflowError: null
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:556) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:556) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:556) ~[forge:?]
```

**Comment by LoneDev6** [comment]
This is only a partial log.
Provide the full log.
