### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by gstio86** [PluginBugs/Issues-CinematicsStudio#25]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

GT86#1000

### What happened?

I installed this plugin on Arclight, but due to the Pixelmon Reforged mod, the highest supported Java version is only 11. Of course, I also use Itemadder, so I thought it might work, but in reality, it cannot be loaded correctly. Cinematic Studio only supports Java 17, which is frustrating for me. I think it should support up to Java 11 like Itemadder.

### Steps to reproduce the issue

Use Java11 and Arclight-1.16.5-1.0.25  run this plugin

### Server version

![image](https://user-images.githubusercontent.com/74390539/229694522-91f43ce1-473b-4b40-a70c-f2af87d1634a.png)

### CinematicsStudio Version

1.4.3-r7

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/74390539/229694626-a638b654-b137-44e4-be95-e7cbb4b7a506.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/74390539/229694712-cc7b6961-962f-4942-ad62-4db523288d56.png)

### Error (optional)

```shell
[04Apr2023 04:51:32.947] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins/CinematicStudio_1.4.3-r7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: dev/lone/cinematicstudio/main/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:149) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:381) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51]
	at net.minecraft.server.dedicated.DedicatedServer.handler$baj000$arclight$loadPlugins(DedicatedServerMixin.java:637) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1878) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: dev/lone/cinematicstudio/main/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoaderMixin.java:644) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:104) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoaderMixin.java:67) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:145) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-c7a91c51]
	... 8 more
```

**Comment by LoneDev6** [comment]
Will be checked as soon as possible

**Comment by gstio86** [comment]
Any updates on this?

**Comment by LoneDev6** [comment]
Sorry for the wait, I've almost finished fixing that.
I'll post an update today :D
Anyway I'm a GT86 fan too!
