### ISSUE TITLE
Error while playing cutscene

### ISSUE THREAD

**Issue by GsTio86** [PluginBugs/Issues-CinematicsStudio#28]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

GT86#1000

### What happened?

An error occurred while playing a cutscene
I have enabled Region Trigger, and an error will occur every time it is triggered

### Steps to reproduce the issue

1. Region Trigger for cutscenes
2. An error occurs whenever triggering

### Server version

![image](https://user-images.githubusercontent.com/74390539/234637694-5f283990-1f0e-4191-bf29-d637bd420288.png)

### CinematicsStudio Version

![image](https://user-images.githubusercontent.com/74390539/234637889-be3013f7-0e0d-4261-81df-4a666f83c290.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/74390539/234638020-24553d2c-c9f6-4aaf-b89d-1ffaf5776f3e.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/74390539/234638152-421bbf02-fbec-4077-8937-f5935d545fc3.png)

### Error (optional)

```[[23:58:58] [Craft Scheduler Thread - 12/WARN] [CinematicStudio/]: Plugin CinematicStudio v1.4.3-r8 generated an exception while executing task 33
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
	at dev.lone.cinematicstudio.cutscene.RegionScheduler.tick(SourceFile:65) ~[CinematicStudio_1.4.3-r8-Fix.jar:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-c7a91c51]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [arclight:arclight-1.16.5-1.0.26-SNAPSHOT-c7a91c51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by LoneDev6** [comment]
will be checked, thanks

**Comment by gstio86** [comment]
When will there be an update
