### ISSUE TITLE
Error while plugin load

### ISSUE THREAD

**Issue by EliGas89** [PluginBugs/Issues-CinematicsStudio#40]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

𝑬𝒍𝒊𝒊𝒎𝒑𝒂#9552

### What happened?

Hello, 
When i start my server, CinematicStudio crash immediatly, and the dependency are stable and updated, i really don't understand.

### Steps to reproduce the issue

I just start the server, and the plugin crash.

### Server version

Purpur 1.19.4

### CinematicsStudio Version

Cinematic Studio version 1.4.3-r8

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[2023-06-19-3.log.gz](https://github.com/PluginBugs/Issues-CinematicsStudio/files/11790829/2023-06-19-3.log.gz)

### Error (optional)

```shell
[00:26:09 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'CinematicStudio_1.4.3-r8.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    dev/lone/cinematicstudio/main/Main.onEnable()V @21: invokedynamic
  Reason:
    Type uninitialized 4 (current frame, stack[1]) is not assignable to 'java/lang/Object'
  Current Frame:
    bci: @21
    flags: { }
    locals: { 'dev/lone/cinematicstudio/main/Main' }
    stack: { uninitialized 4, uninitialized 4, 'dev/lone/cinematicstudio/main/Main', integer }
  Bytecode:
    0000000: 2ab3 001e bb00 6059 2a04 0382 0382 0380
    0000010: 0382 1009 82ba 0073 0000 57b8 0078 b800
    0000020: 7b2a b600 7ebb 0080 59b7 0081 57bb 0083
    0000030: 59b7 0084 57bb 0086 59b7 0087 57bb 0089
    0000040: 59b7 008a 57bb 008c 59b7 008d 57bb 008f
    0000050: 59b7 0090 572a b700 93b8 0098 b800 9ba7
    0000060: 0008 4c2b b800 a1b1                    
  Exception Handler Table:
    bci [33, 95] => handler: 98
  Stackmap Table:
    same_locals_1_stack_item_extended(@98,Object[#94])
    same_frame(@103)
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    dev/lone/cinematicstudio/main/Main.onEnable()V @21: invokedynamic
  Reason:
    Type uninitialized 4 (current frame, stack[1]) is not assignable to 'java/lang/Object'
  Current Frame:
    bci: @21
    flags: { }
    locals: { 'dev/lone/cinematicstudio/main/Main' }
    stack: { uninitialized 4, uninitialized 4, 'dev/lone/cinematicstudio/main/Main', integer }
  Bytecode:
    0000000: 2ab3 001e bb00 6059 2a04 0382 0382 0380
    0000010: 0382 1009 82ba 0073 0000 57b8 0078 b800
    0000020: 7b2a b600 7ebb 0080 59b7 0081 57bb 0083
    0000030: 59b7 0084 57bb 0086 59b7 0087 57bb 0089
    0000040: 59b7 008a 57bb 008c 59b7 008d 57bb 008f
    0000050: 59b7 0090 572a b700 93b8 0098 b800 9ba7
    0000060: 0008 4c2b b800 a1b1                    
  Exception Handler Table:
    bci [33, 95] => handler: 98
  Stackmap Table:
    same_locals_1_stack_item_extended(@98,Object[#94])
    same_frame(@103)
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.19.4.jar:git-Purpur-1985]
        ... 9 more
```

**Comment by LoneDev6** [comment]
> java.lang.VerifyError: Bad type on operand stack
